import sys
from agent.graph import graph

def main():
    print("🚀 AutoStream Agent Initialized (Powered by LangGraph)")
    print("-" * 60)
    
    # LangGraph requires a 'thread_id' to keep track of a specific user's conversation memory
    config = {"configurable": {"thread_id": "user_1"}}

    while True:
        try:
            user_input = input("\nYou: ")

            if user_input.lower().strip() in ['exit', 'quit']:
                print("Shutting down agent... Goodbye! 👋")
                sys.exit(0)
                
            if not user_input.strip():
                continue

            print("Agent is thinking...")
            
            # 1. Invoke the Graph
            result = graph.invoke({"user_input": user_input}, config=config)
            
            # 2. Print the final response generated by the graph
            print(f"\n🤖 AutoStream Agent: {result['response']}")

        except KeyboardInterrupt:
            print("\nShutting down agent... Goodbye! 👋")
            sys.exit(0)

if __name__ == "__main__":
    main()